### ISSUE TITLE
#84题解

### ISSUE THREAD

**Issue by FreemanHsu** [yyypasserby/myleetcode#1]
stack解法好难理解……

**Comment by yyypasserby** [comment]
主要还是理解最中解只会在这些非降序列中出现，如果存在降序，那么一定会包含道非降序接中，剩下就是利用性质剪枝了。我也是看的题解的，并不能想到性质，即使想到性质，要把算法直接设计出来依旧有难度。

**Comment by FreemanHsu** [comment]
我一开始没想明白的是宽度的计算。递增递减的性质似乎遇到过挺多了，从来不会主动想到t.t
